import {test,expect} from '@playwright/test';
test('official location, floor selection, advisory placement and exterior context',async({page},testInfo)=>{
 test.setTimeout(240000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/?studio=1&test=1&quality=light');
 await expect(page.locator('body')).toHaveAttribute('data-studio-mode','complex',{timeout:90000});
 await expect(page.locator('#location-hero')).toBeVisible();
 await expect.poll(()=>page.locator('#location-hero img').evaluate(i=>i.naturalWidth)).toBe(1920);
 await page.screenshot({path:testInfo.outputPath('01-official-location.png')});
 await page.locator('#hero-building').click();
 await expect(page.locator('#floor-rail')).toBeVisible();
 await page.locator('#floor-range').fill('21');await expect(page.locator('#open-unit')).toBeDisabled();
 await page.locator('#floor-rail').hover();await page.mouse.wheel(0,-100);
 await expect(page.locator('#floor-value')).toContainText('22층');
 await expect(page.locator('#open-unit')).toBeEnabled();
 await page.screenshot({path:testInfo.outputPath('02-floor-22.png')});
 await page.locator('#floor-rail [data-floor="22"]').click();await expect(page.locator('body')).toHaveAttribute('data-studio-mode','overview');
 await page.screenshot({path:testInfo.outputPath('03-room-selection.png')});
 await page.locator('#room-edit').click();await page.locator('#selected-item').selectOption('catalog-stool-980');
 const initial=await page.evaluate(()=>window.__studio.inspect());
 const sofa=initial.items.find(i=>i.kind==='sofa');
 await page.locator('#item-x').fill(String(sofa.x));await page.locator('#item-z').fill(String(sofa.z));await page.locator('#apply-position').click();
 let state=await page.evaluate(()=>window.__studio.inspect());
 expect(state.items.find(i=>i.kind==='stool').x).toBe(sofa.x);
 expect(state.positions.find(i=>i.id==='catalog-stool-980').position[0]).toBe(sofa.x);
 await expect(page.locator('#placement-warnings')).toContainText('다른 가구와 겹쳐');
 await page.screenshot({path:testInfo.outputPath('04-overlap-warning.png')});
 await page.locator('#save-layout').click();await page.locator('#reset-layout').click();await page.locator('#restore-layout').click();
 expect((await page.evaluate(()=>window.__studio.inspect())).items.find(i=>i.kind==='stool').x).toBe(sofa.x);
 await page.locator('#reset-layout').click();await page.locator('#selected-item').selectOption('catalog-stool-980');await page.locator('#allow-overlap').uncheck();
 await page.locator('#item-x').fill(String(sofa.x));await page.locator('#item-z').fill(String(sofa.z));await page.locator('#apply-position').click();
 expect((await page.evaluate(()=>window.__studio.inspect())).items.find(i=>i.kind==='stool').x).not.toBe(sofa.x);
 await page.locator('#allow-overlap').check();
 await page.locator('#item-x').fill('2.4');await page.locator('#item-z').fill('2.7');await page.locator('#apply-position').click();
 await expect(page.locator('#placement-warnings')).toContainText('현관문 개방 범위');
 await expect(page.locator('#selected-item')).toHaveValue('catalog-stool-980');
 await page.locator('#reset-layout').click();await page.locator('#room-walk').click();
 await expect.poll(()=>page.evaluate(()=>window.__walkthrough.getState().locked)).toBe(true);
 expect((await page.evaluate(()=>window.__studio.inspect())).exteriorVisible).toBe(true);
 await page.evaluate(()=>{window.__walkthrough.place(6.5,7.5,6.5,15);document.exitPointerLock();});
 await page.screenshot({path:testInfo.outputPath('05-exterior-reference.png')});
 await page.locator('#exterior-enabled').uncheck();expect((await page.evaluate(()=>window.__studio.inspect())).exteriorVisible).toBe(false);
 await page.locator('#exterior-enabled').check();
 await page.locator('#studio-room').selectOption('Entry');await page.locator('#room-walk').click();
 await expect.poll(()=>page.evaluate(()=>window.__walkthrough.getState().locked)).toBe(true);
 expect(await page.evaluate(()=>window.__walkthrough.getState().standing)).toBe(true);
 await page.evaluate(()=>document.exitPointerLock());
 await page.locator('#nav-complex').click();await expect(page.locator('#location-hero')).toBeVisible();
 expect(errors).toEqual([]);
});
