import {test,expect} from '@playwright/test';
test('reference furnishings, metric rooms, balcony access and calibrated human view',async({page},info)=>{
 test.setTimeout(360000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:960});
 await page.goto('/?studio=1&test=1&variant=basic&quality=light');
 await expect(page.locator('body')).toHaveAttribute('data-studio-mode','complex',{timeout:90000});
 await page.locator('#select-building').click();await page.locator('#open-unit').click();
 const items=(await page.evaluate(()=>window.__studio.inspect())).items;
 expect(items.some(i=>i.kind==='single')).toBe(false);
 expect(items.filter(i=>i.kind==='king')).toHaveLength(1);
 expect(items.filter(i=>i.kind==='desk')).toHaveLength(1);
 expect(items.filter(i=>i.kind==='chair')).toHaveLength(1);
 const dims=await page.evaluate(()=>window.__walkthrough.inspectRoom('Bedroom center'));
 expect(dims[0]).toBeCloseTo(2.458,4);expect(dims[2]).toBeCloseTo(2.593,4);
 await expect(page.locator('#studio-room option[value="Living balcony"]')).toHaveCount(1);
 await page.screenshot({path:info.outputPath('01-basic-plan-balconies.png')});
 for(const room of ['Bedroom west','Bedroom center','Living balcony','West open balcony','Center open balcony','Master balcony','Kitchen balcony','Service balcony']){
   await page.locator('#studio-room').selectOption(room);await page.locator('#room-walk').click();
   await expect.poll(()=>page.evaluate(()=>window.__walkthrough.getState().locked)).toBe(true);
   const state=await page.evaluate(()=>window.__walkthrough.getState());
   expect(state.standing).toBe(true);expect(state.pitch).toBeCloseTo(0,6);expect(state.horizontalFov).toBeCloseTo(85,4);
   await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
   if(['Bedroom west','Bedroom center','Living balcony','West open balcony'].includes(room))await page.screenshot({path:info.outputPath(`${room.replaceAll(' ','-')}.png`)});
   await page.evaluate(()=>document.exitPointerLock());
 }
 await page.locator('#studio-room').selectOption('Bedroom west');await page.locator('#room-walk').click();await page.evaluate(()=>document.exitPointerLock());
 await page.locator('#view-settings summary').click();
 await page.locator('#eye').fill('1.65');await page.locator('#body-width').fill('40');
 let state=await page.evaluate(()=>window.__walkthrough.getState());expect(state.eyeHeight).toBe(1.65);expect(state.bodyRadius).toBe(.2);expect(state.headTop).toBeCloseTo(1.77);
 await page.locator('#fov').fill('80');expect((await page.evaluate(()=>window.__walkthrough.getState())).horizontalFov).toBeCloseTo(80,4);
 await page.locator('#projection-mode').selectOption('screen');
 await page.locator('#display-width').fill('32');await page.locator('#view-distance').fill('60');
 const near=(await page.evaluate(()=>window.__walkthrough.getState())).horizontalFov;
 await page.locator('#view-distance').fill('90');expect((await page.evaluate(()=>window.__walkthrough.getState())).horizontalFov).toBeLessThan(near);
 expect(await page.evaluate(()=>window.__walkthrough.inspectRoom('Bedroom center'))).toEqual(dims);
 await page.screenshot({path:info.outputPath('02-personal-view-settings.png')});
 await page.locator('#projection-mode').selectOption('explore');await page.locator('#fov').fill('85');await page.locator('#eye').fill('1.6');await page.locator('#body-width').fill('44');
 await page.locator('#nav-plan').click();await page.locator('#studio-room').selectOption('Bedroom center');await page.locator('#room-edit').click();
 await expect(page.locator('#selected-item')).toContainText('책상');await expect(page.locator('#selected-item')).toContainText('의자');
 await page.screenshot({path:info.outputPath('03-study-edit.png')});
 const warnings=(await page.evaluate(()=>window.__studio.inspect())).warnings;
 expect(warnings.filter(i=>['king-bed','reference-study-desk','reference-study-chair'].includes(i.id)).flatMap(i=>i.messages).some(s=>s.includes('개방 범위'))).toBe(false);
 await page.locator('#nav-complex').click();await page.locator('#select-building').click();await page.locator('#studio-variant').selectOption('expanded');await page.locator('#open-unit').click();
 await expect(page.locator('body')).toHaveAttribute('data-studio-mode','overview',{timeout:90000});
 await expect.poll(()=>page.evaluate(()=>window.__walkthrough.getState().variant),{timeout:90000}).toBe('expanded');
 const expanded=await page.evaluate(()=>window.__walkthrough.inspectRoom('Bedroom center'));
 expect(expanded[0]).toBeCloseTo(2.458,4);expect(expanded[2]).toBeCloseTo(3.083452,4);
 expect((await page.evaluate(()=>window.__studio.inspect())).items.filter(i=>i.kind==='single')).toHaveLength(0);
 await page.screenshot({path:info.outputPath('04-expanded-plan.png')});
 expect(errors).toEqual([]);
});
