import { test, expect } from '@playwright/test';

test('expanded GLB retains meter scale, walkthrough controls and real mesh collisions', async ({ page }, testInfo) => {
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/?test=1');
  await expect(page.locator('body')).toHaveAttribute('data-load-state', 'ready', { timeout: 90000 });
  const state = () => page.evaluate(() => window.__walkthrough.getState());
  const initial = await state();
  expect(initial.scale).toEqual([1, 1, 1]);
  expect(initial.eyeHeight).toBe(1.6);
  expect(initial.meshCount).toBeGreaterThan(450);
  expect(initial.standing).toBe(true);
  const dimensions = await page.evaluate(() => window.__walkthrough.inspectRoom('Bedroom center'));
  expect(dimensions[0]).toBeCloseTo(2.458, 3);
  expect(dimensions[2]).toBeCloseTo(3.0834519, 3);
  await page.screenshot({ path: testInfo.outputPath('expanded-start.png') });
  // Input does nothing until user explicitly enters the walkthrough.
  await page.keyboard.press('w');
  expect((await state()).position).toEqual(initial.position);
  await page.locator('#view-settings summary').click();
  await page.locator('#fov').fill('70');
  await page.locator('#eye').fill('1.7');
  expect((await state()).eyeHeight).toBe(1.7);
  expect((await state()).fov).toBe(70);
  expect((await state()).scale).toEqual([1, 1, 1]);
  await page.locator('#fov').fill('60');
  await page.locator('#eye').fill('1.6');
  await page.locator('#grid').click();
  await expect(page.locator('#grid')).toHaveAttribute('aria-pressed', 'true');
  await page.locator('#grid').click();
  await page.locator('#start').click();
  await expect.poll(async () => (await state()).locked).toBe(true);
  await page.keyboard.down('w');
  await expect.poll(async () => (await state()).position[2], { timeout: 15000 }).toBeGreaterThan(initial.position[2] + 0.15);
  await page.keyboard.up('w');
  await page.evaluate(() => document.exitPointerLock());
  await expect(page.locator('#panel')).toBeVisible();
  await page.locator('#reset').click();
  // Reach the closed glass through the west aisle, clear of the new stool.
  await page.evaluate(() => window.__walkthrough.place(6.35, 6.4, 6.35, 9));
  await page.evaluate(() => window.__walkthrough.move(0, 8));
  const atWindow = await state();
  expect(atWindow.position[2]).toBeGreaterThan(8.9);
  expect(atWindow.position[2]).toBeLessThan(9.3);
  expect(atWindow.standing).toBe(true);
  expect(atWindow.position[1]).toBe(1.6);
  await page.evaluate(() => window.__walkthrough.move(0, 2));
  expect((await state()).position[2]).toBeCloseTo(atWindow.position[2], 3);
  await page.locator('#reset').click();
  expect((await state()).doors).toHaveLength(13);
  await page.evaluate(() => window.__walkthrough.place(4.938, 4.8, 4.938, 5.525));
  expect(await page.evaluate(() => window.__walkthrough.pickDoor())).toBe('acro_0275');
  await page.locator('#start').click();
  await expect.poll(async () => (await state()).locked).toBe(true);
  await page.keyboard.press('e');
  await expect.poll(async () => (await state()).doors.find((d) => d.id === 'acro_0275').progress, { timeout: 60000 }).toBeCloseTo(1, 3);
  await page.evaluate(() => document.exitPointerLock());
  await page.evaluate(() => window.__walkthrough.move(0, 1.5));
  // Clear the door plane at Z=5.525; the updated 2m bed stops travel farther in.
  expect((await state()).position[2]).toBeGreaterThan(6.0);
  expect((await state()).standing).toBe(true);
  // Quality changes only the visual pass, never scale or door/collision state.
  await page.locator('#quality').selectOption('light');
  expect((await state()).quality).toBe('light');
  await page.locator('#quality').selectOption('high');
  expect((await state()).quality).toBe('high');
  expect((await state()).scale).toEqual([1, 1, 1]);
  await page.locator('#reset').click();
  await page.evaluate(() => window.__walkthrough.look(0));
  await page.screenshot({ path: testInfo.outputPath('expanded-kitchen.png') });
  await testInfo.attach('metric-checks', { body: JSON.stringify({ initial, bedroomMeters: dimensions, atWindow }, null, 2), contentType: 'application/json' });
  expect(errors).toEqual([]);
});

test('missing model presents a usable failure message', async ({ page }) => {
  await page.route('**/*.glb', (route) => route.fulfill({ status: 404, body: 'Not found' }));
  await page.goto('/');
  await expect(page.locator('body')).toHaveAttribute('data-load-state', 'error', { timeout: 30000 });
  await expect(page.locator('#start')).toBeDisabled();
  await expect(page.locator('#status')).toContainText('공간을 열지 못했습니다');
});

test('basic/expanded switch preserves presets and uses each model\'s true dimensions and collisions', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1000, height: 800 });
  await page.goto('/?test=1&quality=light');
  const state = () => page.evaluate(() => window.__walkthrough.getState());
  await expect(page.locator('body')).toHaveAttribute('data-load-state', 'ready', { timeout: 90000 });
  await page.locator('#finish').selectOption('oak');
  await expect(page.locator('body')).toHaveAttribute('data-finish-state', 'ready', { timeout: 30000 });
  expect((await state()).finish).toBe('oak');
  const maps = await page.evaluate(() => window.__walkthrough.textureInfo());
  expect(maps.map((m) => m.name).sort()).toEqual(['generated-limestone', 'generated-oak']);
  for (const map of maps) expect([map.width, map.height]).toEqual([1254, 1254]);
  await page.locator('#lighting').selectOption('sunset');
  expect((await state()).lighting).toBe('sunset');
  await page.screenshot({ path: testInfo.outputPath('expanded-oak-sunset.png') });
  await page.locator('#finish').selectOption('stone');
  await expect.poll(async () => (await state()).finish).toBe('stone');
  await page.locator('#lighting').selectOption('night');
  await page.locator('#variant').selectOption('basic');
  await expect.poll(async () => (await state()).variant, { timeout: 60000 }).toBe('basic');
  const basic = await state();
  expect(basic.scale).toEqual([1, 1, 1]);
  expect(basic.doors).toHaveLength(17);
  expect(basic.finish).toBe('stone'); expect(basic.lighting).toBe('night');
  expect(basic.visibleVariants).toBe(1); expect(basic.standing).toBe(true);
  const basicRoom = await page.evaluate(() => window.__walkthrough.inspectRoom('Bedroom center'));
  expect(basicRoom[0]).toBeCloseTo(2.458, 3); expect(basicRoom[2]).toBeCloseTo(2.593, 3);
  await page.screenshot({ path: testInfo.outputPath('basic-stone-night.png') });
  await page.evaluate(() => window.__walkthrough.move(0, 8));
  expect((await state()).position[2]).toBeLessThan(8.1);
  expect((await state()).standing).toBe(true);
  await page.locator('#variant').selectOption('expanded');
  await expect.poll(async () => (await state()).variant).toBe('expanded');
  expect((await state()).visibleVariants).toBe(1);
  expect((await state()).finish).toBe('stone');
  const expandedRoom = await page.evaluate(() => window.__walkthrough.inspectRoom('Bedroom center'));
  expect(expandedRoom[2]).toBeCloseTo(3.0834519, 3);
  await page.locator('#finish').selectOption('original');
  await expect.poll(async () => (await state()).finish).toBe('original');
  expect(await page.evaluate(() => window.__walkthrough.textureInfo())).toEqual([]);
  // URL reflects the actual committed model/presets, so a reload reproduces the choice.
  expect(new URL(page.url()).searchParams.get('variant')).toBe('expanded');
  expect(new URL(page.url()).searchParams.get('lighting')).toBe('night');
  await testInfo.attach('variant-meters', { body: JSON.stringify({ basicRoom, expandedRoom, basic, maps }, null, 2), contentType: 'application/json' });
});

test('failed model or generated texture load keeps the current apartment usable', async ({ page }) => {
  await page.goto('/?test=1&quality=light');
  await expect(page.locator('body')).toHaveAttribute('data-load-state', 'ready', { timeout: 90000 });
  await page.route('**/acro112a-basic.glb', (route) => route.fulfill({ status: 404, body: 'missing' }));
  await page.locator('#variant').selectOption('basic');
  await expect(page.locator('#status')).toContainText('이전 공간을 유지', { timeout: 30000 });
  await expect(page.locator('#variant')).toHaveValue('expanded');
  await expect(page.locator('#start')).toBeEnabled();
  await page.route('**/generated-v1/*.png', (route) => route.fulfill({ status: 404, body: 'missing' }));
  await page.locator('#finish').selectOption('oak');
  await expect(page.locator('#status')).toContainText('이전 마감을 유지', { timeout: 30000 });
  await expect(page.locator('#finish')).toHaveValue('original');
  const current = await page.evaluate(() => window.__walkthrough.getState());
  expect(current.variant).toBe('expanded'); expect(current.finish).toBe('original'); expect(current.standing).toBe(true);
  await expect(page.locator('#start')).toBeEnabled();
});
